[package]
name = "rostermine"
version = "0.1.0"
edition = "2021"

[dependencies]
checksums = "0.9.1"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
zip-extract = "0.2.2"
